apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-php-fpm-configmap
data:
  www.conf: |-
    [www]
    user = www-data 
    group = www-data
    listen = 127.0.0.1:9000
    pm = ondemand
    pm.max_children = 30
    pm.start_servers = 3
    pm.process_idle_timeout = 3s
    pm.min_spare_servers = 2
    pm.max_spare_servers = 5
    pm.max_requests = 200
    env[TMP] = /tmp
    env[TEMP] = /tmp
    php_admin_value[error_log] = /var/log/fpm-php.www.log
    php_admin_flag[log_errors] = on
    listen.owner = www-data
    listen.group = www-data
    php_admin_flag[log_errors] = on
