apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel-app.fullname" . }}
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "laravel-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "laravel-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "laravel-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: {{ .Release.Name }}-nginx-configmap
          configMap:
            name: {{ .Release.Name }}-nginx-configmap
            items:
              - key: default.conf
                path: default.conf
                #- name: {{ .Release.Name }}-php-configmap
                #  configMap:
                #    name: {{ .Release.Name }}-php-configmap
                #    items: 
                #      - key: env
                #        path: .env
        - name: {{ .Release.Name }}-app-shared-data
          emptyDir: {}
      initContainers:
        - name: creating-ephemeral-volume
          image: "{{ .Values.image_debian.repository }}"
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-php-configmap
          volumeMounts:
            - name: {{ .Release.Name }}-app-shared-data
              mountPath: /app
          args: ["/bin/mv","/html/","/app/"]
        - name: config-cache
          image: "{{ .Values.image_php_cli.repository }}:{{ .Values.image_app.tag | default .Chart.AppVersion }}"
          workingDir: /app/html
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-php-configmap
          volumeMounts:
            - name: {{ .Release.Name }}-app-shared-data
              mountPath: /app
          args: ["php","artisan","config:cache"]
              #(php artisan migrate || true) && 
              #(php artisan db:seed || true) && 
              #(php artisan route:cache || true) && 
              #(php artisan view:cache || true) && 
              #(cp -a /var/www/. /artisan-intimaai-web)
              #- artisan
              #- config:cache
          #- name: creating-ephemeral-volume
          #  image: "{{ .Values.image_php_cli.repository }}:{{ .Values.image_app.tag | default .Chart.AppVersion }}"
          #  envFrom:
          #    - configMapRef:
          #        name: {{ .Release.Name }}-php-configmap
          #  volumeMounts:
          #    - name: {{ .Release.Name }}-app-shared-data
          #      mountPath: /app
          #  command: ["/bin/sh"]
          #  args: ["-c","cd","/app","&&","php","artisan","config:cache"]
      containers:
        - name: {{ .Chart.Name }}-app
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image_app.repository }}:{{ .Values.image_app.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image_app.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-php-configmap
          volumeMounts:
            - name: {{ .Release.Name }}-app-shared-data
              mountPath: /app
          workingDir: /app/html
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: {{ .Chart.Name }}-nginx
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image_server.repository }}:{{ .Values.image_server.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image_server.pullPolicy }}
          volumeMounts:
            - name: {{ .Release.Name }}-nginx-configmap
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
          volumeMounts:
            - name: {{ .Release.Name }}-app-shared-data
              mountPath: /app
          workingDir: /app/html
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
            {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
